# Generated by Django 5.2.5 on 2026-07-29 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_roles_and_profiles'),
        ('verticals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vertical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='verticals.vertical'),
        ),
        migrations.AddField(
            model_name='employee',
            name='vertical_locked',
            field=models.BooleanField(default=False),
        ),
    ]
