# Generated by Django 5.2.5 on 2026-07-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_employee_vertical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('agenda', 'Agenda'), ('pacientes', 'Pacientes'), ('medicos', 'Médicos'), ('odontograma', 'Odontograma'), ('consultorios', 'Consultórios'), ('relatorios', 'Relatórios'), ('financeiro', 'Financeiro'), ('configuracoes', 'Configurações'), ('colaboradores', 'Colaboradores'), ('cargos', 'Cargos')], max_length=30),
        ),
    ]
