# Generated by Django 5.2.5 on 2026-08-12 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_rolepermission_module'),
        ('doctors', '0002_council_and_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='doctors.doctor', verbose_name='Profissional vinculado'),
        ),
    ]
