# Generated by Django 5.2.5 on 2026-07-29 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_appointment_vertical'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações gerais')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dental_chart', to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
            },
        ),
        migrations.CreateModel(
            name='ToothRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tooth', models.PositiveSmallIntegerField(verbose_name='Dente')),
                ('face', models.CharField(choices=[('TODO', 'Dente inteiro'), ('VESTIBULAR', 'Vestibular'), ('LINGUAL', 'Lingual'), ('MESIAL', 'Mesial'), ('DISTAL', 'Distal'), ('OCLUSAL', 'Oclusal')], default='TODO', max_length=12, verbose_name='Face')),
                ('condition', models.CharField(choices=[('SAUDAVEL', 'Saudável'), ('CARIE', 'Cárie'), ('RESTAURADO', 'Restaurado'), ('FRATURADO', 'Fraturado'), ('AUSENTE', 'Ausente'), ('IMPLANTE', 'Implante'), ('PROTESE', 'Prótese')], default='SAUDAVEL', max_length=12, verbose_name='Condição')),
                ('procedure', models.CharField(blank=True, max_length=120, verbose_name='Procedimento')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EXECUTADO', 'Executado'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=10, verbose_name='Situação')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tooth_records', to='appointments.appointment', verbose_name='Atendimento')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_records', to='dental.dentalchart')),
            ],
            options={
                'verbose_name': 'Lançamento em dente',
                'verbose_name_plural': 'Lançamentos em dentes',
                'ordering': ['tooth', 'face', '-created_at'],
                'indexes': [models.Index(fields=['chart', 'tooth'], name='dental_toot_chart_i_f926b9_idx')],
            },
        ),
    ]
