# Generated by Django 5.2.5 on 2026-07-29 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('modules', models.JSONField(blank=True, default=list)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vertical',
                'verbose_name_plural': 'Verticais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerticalEmailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=120, verbose_name='Padrão')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('vertical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_rules', to='verticals.vertical')),
            ],
            options={
                'verbose_name': 'Regra de e-mail',
                'verbose_name_plural': 'Regras de e-mail',
                'ordering': ['-priority', 'pk'],
                'unique_together': {('vertical', 'pattern')},
            },
        ),
    ]
